name: Tests

on:

  # Allow calling manually from GitHub
  workflow_dispatch:

  # Allow workflow to be called by another workflow
  workflow_call:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup PNPM with Dependencies
        uses: ./.github/actions/setup-pnpm-with-dependencies/
        with:
          force-install: true

      - name: Stylelint
        run: pnpm run stylelint

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

